# Generated by Django 4.2.1 on 2023-05-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('fullname', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=50)),
                ('nid_no', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
